- name: Numer0nApp
  description: ヌメロンアプリです
  github: https://github.com/SasakiPeter/i-know-your-thinking
  href: https://sasakipeter.github.io/i-know-your-thinking/
  image: /img/Numer0nApp.png
  language: React

- name: ToDoApp
  description: Todoアプリです
  github: https://github.com/SasakiPeter/react-todoapp
  href: https://sasakipeter.github.io/react-todoapp/
  image: /img/TodoApp.png
  language: React

- name: the_sky
  description: 目に優しい神経衰弱です
  github: https://github.com/SasakiPeter/the_sky
  href: https://the-sky-1912.herokuapp.com/
  image: /img/the_sky.png
  language: Python
