- name: Primary
  to: /
  fa: fas fa-home

- name: Posts
  to: /blog/
  fa: fas fa-file-prescription

- name: Products
  to: /products/
  fa: fas fa-capsules

- name: Profile
  to: /about/
  fa: fas fa-id-card-alt
